Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3

In [1]:
import numpy as np

In [6]:
a=np.array([[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],[18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33],[34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49]])

print(a)

[[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


Questions 2:
    
Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it

In [30]:
a=["z","i","s","h","a","n"]
b=["s","a","y","y","e","d"]
name=np.array((a,b))
print(name)
print(np.sort(name))

[['z' 'i' 's' 'h' 'a' 'n']
 ['s' 'a' 'y' 'y' 'e' 'd']]
[['a' 'h' 'i' 'n' 's' 'z']
 ['a' 'd' 'e' 's' 'y' 'y']]


Questions 3:
    
Write a code snippet to find the dimensions of a ndarray and its size

In [11]:
arr=np.array([[1,2,3],[2,3,4],[4,5,6]])
print(np.shape(arr))
print(np.size(arr))

(3, 3)
9


Questions 4:
    
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [17]:
arr=np.array([1,2])
print(np.shape(arr))
print()
x=np.expand_dims(arr,axis=1)
print(x)
print()
print(np.shape(x))

(2,)

[[1]
 [2]]

(2, 1)


Questions 5:
    
Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [21]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


Questions 6:
    
How to get unique items and counts of unique items?

In [24]:
arr=np.array([1,2,3,1,2,3,4,5,6,1,4,5,6])
print(np.unique(arr))
print()

[1 2 3 4 5 6]


In [26]:
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([3, 2, 2, 2, 2, 2], dtype=int64))

# End